name: ozomall_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.2
  provider: 4.3.0
  flutter_swiper: ^1.1.0
  dio: 3.0.0
  shared_preferences: 0.5.10
  flutter_html: ^1.0.0
  loading_indicator_view: ^1.1.0
  flutter_easyloading: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/u=1691093550,1795227220&fm=26&gp=0.jpg
